(()=>{const SANECHKA_EMAIL="michnin.aleksandr.1@gmail.com", F="https://lhfzvwlbnfvictowzvmp.supabase.co/functions/v1/mama-sto-chat",MU="https://lhfzvwlbnfvictowzvmp.supabase.co",MK="sb_publishable_xnF9H_s77aMohEhxmBA_PQ_t8ggXhl0",SU="https://lurjmjgtqogwlxkyauso.supabase.co",SK="sb_publishable_CwQfxteL0l2-xO7UiclS6g_kJ7IcBvk",im=!!document.getElementById("app"),title=im?"Чат с Admin":"Чат с Mama";let c=null,role=null,timer=null,opened=false,last="";
const blocked=()=>{if(im)return false;try{if(typeof window.isSanechkaAccount==="function"&&window.isSanechkaAccount())return true;const raw=localStorage.getItem("sto_supabase_session")||sessionStorage.getItem("sto_supabase_session"),s=raw?JSON.parse(raw):null;return String(s?.user?.email||"").trim().toLowerCase()===SANECHKA_EMAIL}catch(_){return false}};const esc=v=>String(v??"").replace(/[&<>"']/g,x=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[x])),fmt=v=>{try{return new Date(v).toLocaleString("ru-RU",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"})}catch(_){return""}};
function css(){if(document.getElementById("mamaStoChatStyle"))return;const s=document.createElement("style");s.id="mamaStoChatStyle";s.textContent='#mamaStoChatButton{display:none;margin-top:8px;width:auto;min-width:150px;max-width:190px;min-height:42px;padding:8px 14px;font-size:14px;font-weight:800}#mamaStoChatButton.mama-sto-unread{background:#facc15!important;color:#111827!important;box-shadow:0 0 0 3px rgba(250,204,21,.28)}.mama-sto-chat-badge{display:inline-flex;align-items:center;justify-content:center;min-width:20px;height:20px;padding:0 6px;margin-left:5px;border-radius:999px;background:#dc2626;color:#fff;font-size:12px;font-weight:900}.mama-sto-chat-bg{position:fixed;inset:0;background:rgba(15,23,42,.55);display:none;align-items:center;justify-content:center;z-index:100000;padding:16px}.mama-sto-chat-bg.open{display:flex}.mama-sto-chat{width:min(620px,100%);max-height:92vh;background:#fff;border-radius:18px;display:flex;flex-direction:column;overflow:hidden}.mama-sto-chat-head{display:flex;align-items:center;justify-content:space-between;padding:14px 16px;border-bottom:1px solid #e5e7eb;font-weight:900;font-size:18px}.mama-sto-chat-list{padding:14px;overflow:auto;display:flex;flex-direction:column;gap:9px;min-height:260px}.mama-sto-msg{max-width:82%;padding:9px 11px;border-radius:13px;background:#f1f5f9;align-self:flex-start;white-space:pre-wrap;overflow-wrap:anywhere}.mama-sto-msg.mine{align-self:flex-end;background:#dbeafe}.mama-sto-msg.deleted{font-style:italic;color:#64748b}.mama-sto-meta{font-size:11px;color:#64748b;margin-top:4px}.mama-sto-checks{font-weight:900;letter-spacing:-2px;margin-left:4px}.mama-sto-checks.read{color:#2563eb}.mama-sto-msg-actions{display:flex;gap:5px;margin-top:6px}.mama-sto-msg-actions button{font-size:11px;padding:4px 7px}.mama-sto-chat-form{display:flex;gap:8px;padding:12px;border-top:1px solid #e5e7eb}.mama-sto-chat-input{flex:1;min-height:44px;max-height:120px;resize:vertical;padding:9px 10px}.mama-sto-chat-status{font-size:12px;color:#64748b;padding:0 14px 8px;min-height:16px}';document.head.appendChild(s)}
function addButton(){if(blocked()){document.getElementById("mamaStoChatButton")?.remove();document.getElementById("mamaStoChatModal")?.remove();return null}let b=document.getElementById("mamaStoChatButton");if(!b){const h=im?document.querySelector(".actions"):(document.querySelector(".sanechka-main-buttons")||document.querySelector("header"));if(!h)return null;b=document.createElement("button");b.id="mamaStoChatButton";b.className=im?"btn secondary":"developer-messages-button";h.appendChild(b)}b.innerHTML="💬 "+title+' <span class="mama-sto-chat-badge" style="display:none">0</span>';b.onclick=openChat;return b}
function unread(n){const b=document.getElementById("mamaStoChatButton");if(!b)return;const x=Number(n)||0;b.classList.toggle("mama-sto-unread",x>0);const q=b.querySelector(".mama-sto-chat-badge");if(q){q.textContent=x>99?"99+":x;q.style.display=x?"inline-flex":"none"}}
function modal(){if(document.getElementById("mamaStoChatModal"))return;const bg=document.createElement("div");bg.id="mamaStoChatModal";bg.className="mama-sto-chat-bg";bg.innerHTML='<div class="mama-sto-chat"><div class="mama-sto-chat-head"><span>'+esc(title)+'</span><button class="mama-sto-chat-close">✕</button></div><div id="mamaStoChatList" class="mama-sto-chat-list"></div><div id="mamaStoChatStatus" class="mama-sto-chat-status"></div><form id="mamaStoChatForm" class="mama-sto-chat-form"><textarea id="mamaStoChatInput" class="mama-sto-chat-input" maxlength="4000" placeholder="Сообщение..." required></textarea><button class="btn primary">📨</button></form></div>';document.body.appendChild(bg);bg.querySelector(".mama-sto-chat-close").onclick=closeChat;bg.addEventListener("click",e=>{if(e.target===bg)closeChat()});bg.querySelector("form").onsubmit=async e=>{e.preventDefault();const i=document.getElementById("mamaStoChatInput"),t=i.value.trim();if(!t)return;try{await req("send",{body:t});i.value="";await load()}catch(x){status(x.message)}}}
function status(v){const e=document.getElementById("mamaStoChatStatus");if(e)e.textContent=v||""}
async function token(){if(!c){if(im)c=window.supabase.createClient(MU,MK);else{const st={getItem:k=>{try{return localStorage.getItem(k)||sessionStorage.getItem(k)}catch(_){return null}},setItem:(k,v)=>{try{localStorage.setItem(k,v)}catch(_){}},removeItem:k=>{try{localStorage.removeItem(k);sessionStorage.removeItem(k)}catch(_){}}};c=window.supabase.createClient(SU,SK,{auth:{storage:st,persistSession:true,autoRefreshToken:true}})}}const {data,error}=await c.auth.getSession();if(error||!data.session?.access_token){try{const r=localStorage.getItem("sto_supabase_session")||sessionStorage.getItem("sto_supabase_session"),s=r?JSON.parse(r):null;if(s?.access_token)return s.access_token}catch(_){}throw Error("Сессия не найдена. Войдите в приложение.")}return data.session.access_token}
async function req(a,b={}){const t=await token(),r=await fetch(F,{method:a==="get"?"GET":"POST",headers:{Authorization:"Bearer "+t,"Content-Type":"application/json"},body:a==="get"?undefined:JSON.stringify({action:a,...b})}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Ошибка чата");return d}
async function access(){if(blocked())return null;try{const d=await req("get"),ms=Array.isArray(d.messages)?d.messages:[];role=d.role;unread(ms.filter(m=>m.recipient_role===role&&!m.read_at&&!m.deleted_at).length);const b=addButton();if(b)b.style.display="inline-flex";return ms}catch(e){const b=addButton();if(b)b.style.display="inline-flex";console.warn("Чат:",e);return null}}
function html(m){const mine=m.sender_role===role,del=!!m.deleted_at,st=mine?(m.read_at?'<span class="mama-sto-checks read">✓✓</span>':(m.delivered_at?'<span class="mama-sto-checks">✓</span>':'<span class="mama-sto-checks">◷</span>')):"",body=del?"Сообщение удалено":esc(m.body),ed=!del&&m.edited_at?" · изменено":"",act=mine&&!del?'<div class="mama-sto-msg-actions"><button type="button" data-e="'+esc(m.id)+'">✏️ Изменить</button><button type="button" data-d="'+esc(m.id)+'">🗑 Удалить</button></div>':"";return '<div class="mama-sto-msg '+(mine?"mine ":"")+(del?"deleted":"")+'" data-id="'+esc(m.id)+'"><div>'+body+'</div><div class="mama-sto-meta">'+(mine?"Вы":(im?"Admin":"Mama"))+" · "+esc(fmt(m.created_at))+ed+st+'</div>'+act+'</div>'}
async function load(){const ms=await access();if(!ms)return;const sig=ms.map(m=>[m.id,m.edited_at,m.deleted_at,m.delivered_at,m.read_at].join(":")).join("|");if(sig===last&&!opened)return;last=sig;const l=document.getElementById("mamaStoChatList");if(!l)return;l.innerHTML=ms.length?ms.map(html).join(""):'<div style="color:#64748b;text-align:center;padding:40px 10px">Пока сообщений нет.</div>';l.querySelectorAll("[data-e]").forEach(b=>b.onclick=()=>edit(b.dataset.e));l.querySelectorAll("[data-d]").forEach(b=>b.onclick=()=>del(b.dataset.d));l.scrollTop=l.scrollHeight}
async function edit(id){const e=document.querySelector('.mama-sto-msg[data-id="'+CSS.escape(id)+'"]'),cur=e?.firstElementChild?.textContent||"",v=prompt("Изменить сообщение:",cur);if(v===null||!v.trim())return;try{await req("edit",{id,body:v.trim()});await load()}catch(x){status(x.message)}}
async function del(id){if(!confirm("Удалить это сообщение?"))return;try{await req("delete",{id});await load()}catch(x){status(x.message)}}
async function openChat(){if(blocked())return;modal();document.getElementById("mamaStoChatModal").classList.add("open");opened=true;await load();try{await req("read");unread(0);await load()}catch(e){console.warn("read:",e)}document.getElementById("mamaStoChatInput")?.focus()}
function closeChat(){document.getElementById("mamaStoChatModal")?.classList.remove("open");opened=false}
async function init(){if(!window.supabase||blocked())return;css();addButton();modal();await load();clearInterval(timer);timer=setInterval(load,1800);document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible")load()})}
window.mamaStoChat={open:openChat,close:closeChat,refresh:load};setInterval(()=>{if(blocked()){document.getElementById("mamaStoChatButton")?.remove();document.getElementById("mamaStoChatModal")?.remove();return}if(!document.getElementById("mamaStoChatButton"))addButton()},1000);(function boot(){if(window.supabase)init();else setTimeout(boot,150)})();
})();